CREATE TABLE IF NOT EXISTS profile (
    id CHAR (36) NOT NULL PRIMARY KEY DEFAULT (UUID()),
    name VARCHAR (255) NOT NULL,
    gender VARCHAR (255) NOT NULL,
    email VARCHAR (255) NOT NULL,
    role VARCHAR (255) NOT NULL,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);